# api/config/packages/security.yaml
security:
    encoders:
        App\Entity\Patient: bcrypt
        App\Entity\Tester: bcrypt
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        database:
            entity:
                class: App\Entity\Patient
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: database
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: identifier
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }