# api/config/packages/security.yaml
security:
    encoders:
        App\Entity\Patient:
            algorithm: auto
        App\Entity\Tester:
            algorithm: auto
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        database:
            entity:
                class: App\Entity\Patient
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: database
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: identifier
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator
                    - App\Security\TokenAuthenticator

            user_checker: App\Security\PatientEnabledChecker
        admin:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: security_login
                login_path: security_login
                default_target_path: /admin
                use_referer: true
            logout:
                path: security_logout

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }


    role_hierarchy:
        ROLE_ADMIN: [ROLE_WRITER, ROLE_EDITOR]
        ROLE_SUPERADMIN: ROLE_ADMIN