vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # decide how uploaded files should be renamed
            namer: vich_uploader.namer_uniqid
